### started 11/07/22
#### CNN
##### translation invariance - NN should respond to the same pattern, no matter where it is located
##### yearly layers conscentrated on local regions 

In [6]:
# 6.2 Convolutions for Images
from d2l import mxnet as d2l
from mxnet import autograd, np, npx
from mxnet.gluon import nn
npx.set_np()

In [7]:
def corr2d(X, K):
    """Compute 2D cross-correlation.
    K - kernel
    X - matrix of weights 
    (Nh − Kh + 1) × (Nw − Kw + 1) - > output size of convolutional operation 
    """
    h, w = K.shape
    Y = np.zeros((X.shape[0] - h + 1, X.shape[1] - w + 1))
    for i in range(Y.shape[0]):
        for j in range(Y.shape[1]):
            Y[i, j] = d2l.reduce_sum((X[i: i + h, j: j + w] * K))
    return Y
X = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = np.array([[0.0, 1.0], [2.0, 3.0]]) 
corr2d(X, K)

array([[19., 25.],
       [37., 43.]])

In [8]:
class conv2d(nn.Block): # create conv layer
    def __init__(self, kernel, **kwargs):
        super().__init__(**kwargs)
        self.ww = self.params.get('ww', shape=kernel)
        self.bb = self.params.get('bb', shape=(1,))
    def forward(self, X):
        return corr2d(X, self.ww.data()) + self.bb.data()
        
conv2d = conv2d((1, 2))
conv2d.initialize()
conv2d(X)

array([[0.03792691, 0.0928258 ],
       [0.20262358, 0.25752246],
       [0.3673202 , 0.42221913]])

In [9]:
# edge detector
num = np.ones((3,3))
num[:, 2:3] = 0
kernel = np.array([[1,-1]])
corr2d(num, kernel), num

(array([[0., 1.],
        [0., 1.],
        [0., 1.]]),
 array([[1., 1., 0.],
        [1., 1., 0.],
        [1., 1., 0.]]))